server:
  port: ${PORT:8082}
spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pharmacy_product}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:${DB_USER:root}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:2205}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html


