server:
  port: ${PORT:8082}
spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:bqznwk6pichvxngkotgk-mysql.services.clever-cloud.com}:${DB_PORT:3306}/${DB_NAME:bqznwk6pichvxngkotgk}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:${DB_USER:u7mfxjqcy1huiyvw}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:fsJUQC7iu4Q9f20lMSlu}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html


