server:
  port: ${PORT:8082}
spring:
  application:
    name: product-service
  datasource:
    url:  jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pharmacy_product}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2205}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html


