server:
  port: ${PORT:8083}
spring:
  application:
    name: cart-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pharmacy_cart}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:2205}}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html


